MODULES=(btrfs virtio_pci virtio_blk nvme ahci xhci_pci usbhid hid_generic)
BINARIES=()
FILES=()
HOOKS=(base systemd autodetect microcode modconf keyboard sd-vconsole block sd-encrypt filesystems fsck)
COMPRESSION="zstd"
